# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Champion(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, backspash_url: str=None):  # noqa: E501
        """Champion - a model defined in Swagger

        :param name: The name of this Champion.  # noqa: E501
        :type name: str
        :param backspash_url: The backspash_url of this Champion.  # noqa: E501
        :type backspash_url: str
        """
        self.swagger_types = {
            'name': str,
            'backspash_url': str
        }

        self.attribute_map = {
            'name': 'name',
            'backspash_url': 'backspashUrl'
        }
        self._name = name
        self._backspash_url = backspash_url

    @classmethod
    def from_dict(cls, dikt) -> 'Champion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Champion of this Champion.  # noqa: E501
        :rtype: Champion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Champion.


        :return: The name of this Champion.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Champion.


        :param name: The name of this Champion.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def backspash_url(self) -> str:
        """Gets the backspash_url of this Champion.


        :return: The backspash_url of this Champion.
        :rtype: str
        """
        return self._backspash_url

    @backspash_url.setter
    def backspash_url(self, backspash_url: str):
        """Sets the backspash_url of this Champion.


        :param backspash_url: The backspash_url of this Champion.
        :type backspash_url: str
        """

        self._backspash_url = backspash_url
